Repository UBC-MDS/laundRy, pull requests merged in 2020-03, with the labels that each got.

#28 column_transformer function and its test suite
  DESCRIPTION
  NAMESPACE
  R/categorize.R
  R/column_transformer.R
  R/feature_selection.R
  man/column_transformer.Rd
  tests/testthat/helper_function_column_transformer.R
  tests/testthat/test_column_transformer.R
Labels: enhancement, group

#44 remove second example from readme for fill missing
  README.md
Labels: documentation, enhancement

#50 integration tests added
  tests/testthat/helper_integration_test.R
  tests/testthat/test_integration.R
Labels: enhancement

#68 Implemented peer feedback
  R/column_transformer.R
  man/column_transformer.Rd
  tests/testthat/helper_function_column_transformer.R
  tests/testthat/helper_integration_test.R
  tests/testthat/test_column_transformer.R
  tests/testthat/test_integration.R
Labels: enhancement
